version: '3.7'

services:
  postgresql:
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql:Z
    environment:
      - DB_USER=gitlab
      - DB_PASS=StrongDBPassword
      - DB_NAME=gitlab_production
      - DB_EXTENSION=pg_trgm,btree_gist

  gitlab:
    restart: always
    image: sameersbn/gitlab:14.10.2
    depends_on:
      - redis
      - postgresql
    ports:
      - "10080:80"
      - "10022:22"
    volumes:
      - gitlab-data:/home/git/data:Z
    healthcheck:
      test: curl http://localhost/-/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    environment:
      - DEBUG=false

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=StrongDBPassword
      - DB_NAME=gitlab_production
  atlantis:
    depends_on:
      - gitlab
    #    build:
    #      context: ./
    #      dockerfile: Dockerfile
    ports:
      - "4141:4141"
    image: "ghcr.io/runatlantis/atlantis:v0.21.0"
    command:
      - server
      - --ssl-cert-file="/etc/ssl/certs/my-cert.crt"
      - --ssl-key-file="/etc/ssl/private/my-cert.key"
      - --atlantis-url="http://localhost:4141"
      - --gitlab-hostname=gitlab
      - --gitlab-webhook-secret="12345"
      - --gitlab-user="root"
      - --gitlab-token="glpat-EC6Stbc3DnxsAPhnXw_y"
      - --repo-allowlist='*'
      - --repo-config=/config/repos.yaml
      - --repo-config=/config/repos.yaml

    volumes:
      - $PWD/config/:/config/
