FROM ghcr.io/runatlantis/atlantis:v0.21.0

RUN apk add --no-cache aws-cli

RUN aws --version   # Just to make sure its installed alright


#ENTRYPOINT ["docker-entrypoint.sh"]
#CMD ["server"]


